from setuptools import setup, find_packages

setup(
    name="ml-challenge-2025",
    version="1.0.0",
    author="Sunil Sharma",
    author_email="contact@sunilsharma.dev",
    description="Smart Product Pricing Challenge - ML Challenge 2025",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/sunbyte16/ml-challenge-2025",
    packages=find_packages(),
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.8",
    install_requires=[
        "pandas>=1.5.0",
        "numpy>=1.21.0",
        "scikit-learn>=1.1.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "tensorflow>=2.10.0",
        "torch>=1.12.0",
        "Pillow>=9.0.0",
        "tqdm>=4.64.0",
        "requests>=2.28.0",
    ],
)